# Generated by Django 3.2.6 on 2026-07-17 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tech_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_part', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty_type', models.CharField(blank=True, choices=[('Carrier', 'Carrier'), ('Ferguson', 'Ferguson'), ('Goodman', 'Goodman'), ('Honeywell', 'Honeywell'), ('Lennox', 'Lennox'), ('Mitsubishi', 'Mitsubishi'), ('Trane', 'Trane'), ('Quality Air', 'Quality Air')], max_length=100, null=True)),
                ('claim_number', models.CharField(blank=True, max_length=100, null=True)),
                ('claim_submission_date', models.DateField(blank=True, null=True)),
                ('claim_approval_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('COMPLETED/PAID WARRANTY CLAIM', 'COMPLETED/PAID WARRANTY CLAIM'), ('NO CREDIT RECEIVED', 'NO CREDIT RECEIVED'), ('CLAIM NOT COMPLETED or PAID', 'CLAIM NOT COMPLETED or PAID'), ('SHIPPING NOT PAID IN CLAIM', 'SHIPPING NOT PAID IN CLAIM'), ('NO INVOICE FOR PART = NO CREDIT', 'NO INVOICE FOR PART = NO CREDIT'), ('REQUIRES DISTRIBUTOR REVIEW', 'REQUIRES DISTRIBUTOR REVIEW'), (' REPAIR EXCEEDS NORMAL LIMITS', ' REPAIR EXCEEDS NORMAL LIMITS'), ('WAITING ON CHAD', 'WAITING ON CHAD')], max_length=100, null=True)),
                ('vendor_submission_method', models.CharField(blank=True, choices=[('ServiceBench', 'ServiceBench'), ('Ferguson Portal', 'Ferguson Portal'), ('Email', 'Email'), ('Other Portal', 'Other Portal'), ('Phone', 'Phone'), ('Not Submitted', 'Not Submitted')], max_length=100, null=True)),
                ('vendor_confirmation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_submitted_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='media/invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
